// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/passport-facebook/passport-facebook.d.ts
// Type definitions for passport-facebook 1.0.3
// Project: https://github.com/jaredhanson/passport-facebook
// Definitions by: James Roland Cabresos <https://github.com/staticfunction>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

// Modified by Jeremy-Doucet to include: passReqToCallback

declare module 'passport-facebook' {

    import passport = require('passport');
    import express = require('express');

    interface IProfile extends passport.Profile {
        gender: string;
        profileUrl: string;
        username: string;

        _raw: string;
        _json: any;
    }

    interface IStrategyOption {
        clientID: string;
        clientSecret: string;
        callbackURL: string;

        passReqToCallback?: boolean;
        scopeSeparator?: string;
        enableProof?: boolean;
        profileFields?: string[];
    }

    class Strategy implements passport.Strategy {
        constructor(options: IStrategyOption,
                    verify: (req: boolean, accessToken: string, refreshToken: string, profile: IProfile, done: (error: any, user?: any) => void) => void);
        name: string;
        authenticate: (req: express.Request, options?: Object) => void;
    }
}
